### ISSUE TITLE
Error Object(...) is not a function

### ISSUE THREAD

**Issue by arctic-hare** [Vuepic/vue3-date-time-picker#1]
![Screenshot_33](https://user-images.githubusercontent.com/20585110/131547957-0108a697-f8cb-4a89-be4b-d9c8640f6259.jpg)

**Comment by arctic-hare** [comment]
I use vue-cli 4.5.0
I do import and register component and I get the error

**Comment by arctic-hare** [comment]
"dependencies": {
    "@kyvg/vue3-notification": "^2.3.3",
    "@sape/vue-ui": "^1.8.47",
    "@sentry/browser": "^5.17.0",
    "@sentry/integrations": "^5.17.0",
    "@vee-validate/i18n": "^4.3.2",
    "@vee-validate/rules": "^4.1.20",
    "@vueform/multiselect": "^2.0.1",
    "@vueform/slider": "^2.0.3",
    "axios": "^0.21.1",
    "bootstrap": "^4.6.0",
    "chart.js": "^3.3.2",
    "click-outside-vue3": "^4.0.1",
    "core-js": "^3.6.5",
    "hotkeys-js": "^3.8.7",
    "lscache": "^1.3.0",
    "mitt": "^2.1.0",
    "normalize.css": "^8.0.1",
    "pt-sans-cyrillic": "0.0.4",
    "qs": "^6.10.1",
    "register-service-worker": "^1.7.1",
    "style-resources-loader": "^1.4.1",
    "swagger-client": "^3.13.2",
    "v-tooltip": "^4.0.0-alpha.1",
    "vee-validate": "^4.4.4",
    "vue": "^3.0.0",
    "vue-i18n": "^9.1.6",
    "vue-router": "^4.0.0-0",
    "vue-tel-input": "^6.0.0-beta.0",
    "vue-universal-modal": "^1.1.3",
    "vue-upload-component": "^3.0.50",
    "vue3-date-time-picker": "^1.0.2",
    "vue3-quill": "^0.2.6",
    "vue3-tel-input": "^1.0.4",
    "vuex": "^4.0.0-0",
    "vuex-persistedstate": "^4.0.0-beta.3",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-e2e-cypress": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-pwa": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-unit-jest": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-airbnb": "^5.0.2",
    "@vue/test-utils": "^2.0.0-0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-vue": "^7.0.0",
    "lint-staged": "^9.5.0",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "stylus": "^0.54.7",
    "stylus-loader": "^3.0.2",
    "svg-sprite-loader": "^6.0.6",
    "vue-jest": "^5.0.0-0"
  },

**Comment by Jasenkoo** [comment]
This is strange, I can't reproduce it, can you show me the full component code?

**Comment by wT-** [comment]
I had the same error while using Yarn. Nuking node_modules and using npm instead worked though, for whatever reason

**Comment by Jasenkoo** [comment]
Can you tell me the yarn version used?

**Comment by Jasenkoo** [comment]
Detected issue. This is not the issue with the npm nor the yarn.

From vue [3.2 release](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md#320-2021-08-09) there are some compatibility changes

> code generated by the template compiler in >= 3.2 will not be compatible with runtime < 3.2 

Updating Vue to at least 3.2 will fix the issue.  Since Vue in your cases is installed with ^. Simply remove node_models and lock file and install again.

**Comment by wT-** [comment]
Oh yeah, the package-lock.json was of course newer and yarn.lock was from before, d'oh.
Got my small project working with yarn too now, thanks for the help!

**Comment by arctic-hare** [comment]
+1
Thanks, the update Vue solved the problem.
