### ISSUE TITLE
Cannot combine text input and range

### ISSUE THREAD

**Issue by Nemega** [Vuepic/vue3-date-time-picker#101]
**Describe the bug**
Editing a range directly using the input text resets it to 2002-01-01 00:00

**Steps to reproduce the behavior**
1. Select a date
2. Change it by using the input text
3. Unfocus

**Expected behavior**
Date correctly parsed

 - Browser: chrome
 - Version: 98.0.4758.82

Thank you for investigating this issue. If you need any more info, let me know

**Comment by Jasenkoo** [comment]
@Nemega Can you provide more context, did you use the `autoApply` prop, maybe some code demo I can take a loo? Since it works fine on my end.

**Comment by Nemega** [comment]
Sorry I forgot to mention that the issue only seems to appear when the prop `format` is used (*yyyy-MM-dd HH:mm* in my case). `textInput`, `range` and `autoApply` is also used as well
