### ISSUE TITLE
Events to fetch additional data when month or year changes

### ISSUE THREAD

**Issue by rutwikGit** [Vuepic/vue3-date-time-picker#107]
In my use-case we need to show the calendar with additional data for each day of the calendar e.g. amounts per day.
I do it by calling API and display that for each day of the calendar. So part of initial load, I fetch it for first month that is being displayed. So as the user moves from one month to another, I need a means to call the API to fetch data for subsequent months.

**Describe the solution you'd like**
If event can be emitted whenever month, year being displayed on screen changes, either by arrow keys or via month/year selection overlays

**Describe alternatives you've considered**
Tried hooking onto "monthYearSelect" event, but that seems tobe internal user only.

**Comment by Jasenkoo** [comment]
Will add it

**Comment by rutwikGit** [comment]
Thank you :)

**Comment by gerritvanaaken** [comment]
Great! Can’t wait to test this in 2.8.0
