### ISSUE TITLE
autoApply(props) and action-row-component(component) do not use concurrently

### ISSUE THREAD

**Issue by ngale179** [Vuepic/vue3-date-time-picker#111]
When I use autoApply(props) and action-row-component(component) but action-row-component not working. 
And when I remove autoApply then action-row-component working.
I want to use action-row-component and auto appy seleted date when choose date.
Can help me. Thanks
![image](https://user-images.githubusercontent.com/24906005/156295973-b01c1a3b-2303-42fe-964d-b3314d14a9e9.png)

**Comment by Jasenkoo** [comment]
Leave it open, will close on publish
