### ISSUE TITLE
textInputOptions.menuOpen=false does nothing unless combined with openMenuOnFocus=false

### ISSUE THREAD

**Issue by scythianfeather** [Vuepic/vue3-date-time-picker#120]
### To Reproduce
Click on the input field, comparing:
`<Datepicker
      v-model="date"
      textInput
      :textInputOptions="{ openMenu: false }"
/>`
With:
`<Datepicker
      v-model="date"
      textInput
      :textInputOptions="{ openMenu: false }"
      :openMenuOnFocus="false"
/>`

### Expected Behavior
As per the [textInputOptions documentation](https://vue3datepicker.com/api/props/#textinputoptions), I thought it should be enough to set `textInputOptions.openMenu=false` to prevent the menu from opening when the input field is clicked.

**Comment by Jasenkoo** [comment]
The issue is fixed, please switch to the new package https://github.com/Vuepic/vue-datepicker
