### ISSUE TITLE
position: left, center, right

### ISSUE THREAD

**Issue by onno-timmerman** [Vuepic/vue3-date-time-picker#125]
I seem not be able to make the position work. Nor with altposition. 
Maybe i miss something the annoying thing is that the datepicker is close to the right browser border. And with center the picker is just over the viewable part.

I think left and right are switched. Entering position right give diserble effect. and moves popup to left.

(btw: this is a great datepicker)

**Comment by Jasenkoo** [comment]
Tnx for the compliment 😄 . I will check what is going on there

**Comment by Jasenkoo** [comment]
Turns out it is not an issue, since the menu will be aligned to the left/right border of the input element. In your case, right is the correct prop to pass
