### ISSUE TITLE
openMenu() has unexpected toggle behavior

### ISSUE THREAD

**Issue by scythianfeather** [Vuepic/vue3-date-time-picker#126]
I would expect that calling openMenu() would just set it to be open. In my use case, I'm listening for two events that sometimes both fire simultaneously, and I'd like to open the menu when one or both fire.

https://github.com/Vuepic/vue3-date-time-picker/blob/ba832e90597e2bc2c3d15776cc9800ec59d746f8/src/Vue3DatePicker/Vue3DatePicker.vue#L322

**Comment by Jasenkoo** [comment]
Will see where it is called and adjust

**Comment by Jasenkoo** [comment]
The issue is fixed, please switch to the new package https://github.com/Vuepic/vue-datepicker

**Comment by scythianfeather** [comment]
Thank you!
