### ISSUE TITLE
Setting minDate disables the desired minimum date

### ISSUE THREAD

**Issue by anne-marcotte** [Vuepic/vue3-date-time-picker#128]
**Describe the bug**
When setting the minimum date on the date picker via `minDate` prop, I cannot select the day of the actual minimum date. This does not fit the description of the prop provided in the docs:
> minDate
> All dates before the given date will be disabled

**To Reproduce**

1. Go to https://vue3datepicker.com/api/props/#mindate
2. Note the example uses today's date for `minDate`
3. Open date picker example
4. Note that today's date is disabled, and hovering over the date changes the cursor to reflect the disabled state.

**Expected behavior**
I expect to be able to select the actual day of the minimum date, while all days before the minimum date are disabled

**Code**
```
<template>
    <Datepicker v-model="date" :minDate="new Date()" />
</template>

<script>
import { ref } from 'vue';

export default {
    setup() {
        const date = ref(new Date());
        
        return {
            date,
        }
    }
}
</script>
```

**Screenshots**
<img width="775" alt="Screen Shot 2022-03-17 at 10 07 50 PM" src="https://user-images.githubusercontent.com/81819977/158924046-2cfc30a0-79bf-41e9-819b-36fd9a6a82e9.png">

**Desktop (please complete the following information):**
 - macOS Big Sur 11.6.4
 - Chrome
 - Version 99.0.4844.51

**Comment by Jasenkoo** [comment]
@anne-marcotte Hmm, strange, today should be enabled, can you tell me your timezone so I can check? From my side, I can select today.

**Comment by anne-marcotte** [comment]
@Jasenkoo thanks for taking a look. I'm Eastern Daylight Time (New York)

**Comment by Jasenkoo** [comment]
Tnx for answer, this might be due to a time change last weekend

**Comment by Jasenkoo** [comment]
The issue is fixed, please switch to the new package https://github.com/Vuepic/vue-datepicker

**Comment by anne-marcotte** [comment]
> The issue is fixed, please switch to the new package https://github.com/Vuepic/vue-datepicker

Thank you very much!
