### ISSUE TITLE
`font-size` is a too small

### ISSUE THREAD

**Issue by RyanNorooz** [Vuepic/vue3-date-time-picker#13]
### **Why this happens**
For default `1rem` is `16px`
It is common to use `html{ font-size: 62.5% }`
This makes the `1rem` be equal to `10px` which is easier to work with

### **The problem:**
This plugin uses `rem` for font sizes all over the place thus everything is smaller

### **Describe the solution you'd like**
The plugin could use font sizes with `em` so that the base font size could be set by the parent element font size
or have a sass configurable font-size which i think is a better solution

### **Alternatives i've been using**
I've been manually changing font sizes for every small text in the datepicker component
which is cumbersome af

**Comment by Jasenkoo** [comment]
The new version [2.1.5](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.1.5) is live with included support for `font-size` variables.
