### ISSUE TITLE
How to responsive item when mobile?. dp__calendar it's broken when mobile, is hiding on the left.

### ISSUE THREAD

**Issue by trandinhhuong** [Vuepic/vue3-date-time-picker#130]
![image](https://user-images.githubusercontent.com/68776351/161466872-f9184e10-1ad4-4dc4-ab9c-adc3a0f1eb2f.png)

**Comment by Jasenkoo** [comment]
This package is discontinued, please update to [this package](https://github.com/Vuepic/vue-datepicker)

Also, you can add prop `align="left"` to align the calendar to the left border.

**Comment by Jasenkoo** [comment]
WIll transfer this to the new repository, and will make it work with auto-positioning, so that alignment is done on the x-axis also.
