### ISSUE TITLE
Date picker pop up appears underneath the modal window

### ISSUE THREAD

**Issue by moreorover** [Vuepic/vue3-date-time-picker#15]
**Describe the bug**
I'm building a website using [Bulma CSS](https://bulma.io) framework to help me with styles and have come across the issue when using [modal component](https://bulma.io/documentation/components/modal/). What it does is that when clicked on field to select date, the calendar pop up window appears underneath the modal. It can also be seen in the picture https://i.imgur.com/lfISIhv.png

**To Reproduce**
Steps to reproduce the behaviour:
Clone repo https://github.com/moreorover/vue3-date-time-picker-boiled install dependencies, serve the app, in the home page there is a button, press it, modal will show up, press on the field to pick date. A calendar pop up window will appear underneath the modal window.

**Expected behaviour**
Calendar pop up window expected to be on top of everything allowing user to pick date.

**Screenshots**
https://i.imgur.com/lfISIhv.png

**Comment by Jasenkoo** [comment]
The issue is fixed

New version [2.1.6](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.1.6) is now live
