### ISSUE TITLE
Using modal calendar window opens at the top of the page even if page is scrolled

### ISSUE THREAD

**Issue by moreorover** [Vuepic/vue3-date-time-picker#18]
**Describe the bug**
When using modal, the calendar pop up window always opens at the top centre of the page, regardless of the page scroll position.

**To Reproduce**
Steps to reproduce the behaviour:
1. Reproduction https://github.com/moreorover/vue3-date-time-picker-boiled
2. Go to home page.
3. Scroll down the page.
4. Open modal using a button in the table.
5. Click on date input field to open a calendar pop up window.
6. Calendar window opens at the very top of the page and is not visible if the page is scrolled.

**Expected behaviour**
Calendar window to open underneath the input field even if the page is scrolled.

**Screenshots**
https://i.imgur.com/eE7WTT8.gif

**Comment by Jasenkoo** [comment]
It is strange, I will check it tomorrow, tnx for reporting

**Comment by moreorover** [comment]
No problem, you are welcome. Happy to help.

**Comment by Jasenkoo** [comment]
The issue occurred because Bulma's modal is in a fixed position, meaning it will always return the same value from the top, no matter how much the page is scrolled. I have a fix ready, just to test few more cases. Probably will be published tomorrow afternoon.

**Comment by Jasenkoo** [comment]
The issue is fixed.

New version [2.1.7](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.1.7) is now live.
