### ISSUE TITLE
Wrong import in documentation

### ISSUE THREAD

**Issue by anatolykopyl** [Vuepic/vue3-date-time-picker#23]
[The scss theming page](https://vue3datepicker.com/customization/scss/) has this string as the main `.scss` file import:
```
@import 'vue3-date-time-picker/src/Vue3DatePicker/styles/main.scss';
```
when in reality it should be 
```
@import 'vue3-date-time-picker/src/Vue3DatePicker/style/main.scss';
```

**Comment by Jasenkoo** [comment]
Tnx for reporting, will be corrected.
