### ISSUE TITLE
Methods are not working

### ISSUE THREAD

**Issue by videk11** [Vuepic/vue3-date-time-picker#30]
Hello,

I am trying to use openMenu method on date-picker. When I call it on date-picker ref nothing happens. This is my code:

Template:
`<Datepicker ref="datePickerRef" />`

Setup:
`const datePickerRef = ref(null);`

`const openDatePicker = () => {
			datePickerRef.value.openMenu();
		};`

**Comment by Jasenkoo** [comment]
The issue is fixed in the new version [2.3.2](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.2)
