### ISSUE TITLE
When the text input is cleared and tab is pressed, the value model of the component is not set to `null`

### ISSUE THREAD

**Issue by entioentio** [Vuepic/vue3-date-time-picker#32]
**Describe the bug**
When the text input is cleared and tab is pressed, the value model of the component is not set to `null`

**Comment by weskubo-cgi** [comment]
I've been testing this change on 2.3.5 and noticed that the change doesn't apply when clearing out an existing value. Here's the scenarios I tested:

1. Select new value using Calendar. Value is correctly applied.
2. Type in new value and tab out. Value is correct applied.
3. Type in new value and hit enter.  Value is correct applied.
4. Type in new value and click elsewhere on screen. Value is correctly applied.
5. Clear existing value using (x). Value is set to null.
6. Clear existing value by deleting text and tab out. Value is set to null.
7. Clear existing value by deleting text and hit enter. Value is set to null.
7. Remove existing value by deleting text and click elsewhere on screen. Original value is maintained.

Note, the last scenario fails. I have a simple example at https://codesandbox.io/s/vue3-date-time-picker-demo-forked-s2ic9. Please let me know if you want me to create a new Issue if this is indeed a bug.

**Comment by Jasenkoo** [comment]
Thx for the detailed explanation. I will check it later today

**Comment by Jasenkoo** [comment]
Yeah, it stays. I will fix it in the next version

**Comment by Jasenkoo** [comment]
Fixed removing scenario in [v2.3.6](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.6)

**Comment by weskubo-cgi** [comment]
@Jasenkoo Thanks for the prompt fix. I've already incorporated it into our application.
