### ISSUE TITLE
Leaving a field doesn't auto-apply the value

### ISSUE THREAD

**Issue by entioentio** [Vuepic/vue3-date-time-picker#34]
**Is your feature request related to a problem? Please describe.**
Once more about auto-applying value. My use-case is as follows: user clicks on the input, types the text and leaves the input clicking on another input. The value is not applied, because there's neither tab, nor enter. Do you have any ideas on how could this be solved?

**Comment by Jasenkoo** [comment]
Hmm, I can add another option in `text-input-options` to auto-apply when the date is valid. What do you think?

**Comment by entioentio** [comment]
I think it's a good idea for an UX improvement, but I kinda have a feeling that it's getting out of hand quickly. I mean - how many more text-input-options would there be to come..? When I saw auto-apply prop at first in the docs, was sure it's for this thing. Maybe replacing `enterSubmit` and `tabSubmit` with `textInputOptions: { autoApplyValid: Bool }` would work better? /shrug

**Comment by Jasenkoo** [comment]
Probably better, will make `auto-apply` prop to work with text input. Will leave `enterSubmit` and `tabSumbit` as it is for now.

Thx for the feedback.

**Comment by Jasenkoo** [comment]
Added in the new version [2.3.3](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.3)
