### ISSUE TITLE
Time-picker with min-time and max-time props is not working correctly

### ISSUE THREAD

**Issue by ekkode** [Vuepic/vue3-date-time-picker#38]
**Describe the bug**
Time-picker with min-time and max-time props together with a default time set. When the time-picker is opened is showing the browser time, not the time that was set by default. This is true also when the time was set pragmatically. 

**To Reproduce**
The min-time / max-time props are set and also a default time. 
Now when I click on the time-picker, the value displayed is current time of the browser and not that that was set by default.
Please check here: https://codesandbox.io/s/vue3-date-time-picker-demo-forked-j3qee?file=/src/components/Demo.vue

**Expected behavior**
I want that the time should start from the time configured not jumping to the browser time.
This is happening in version 2.3.3

**Comment by Jasenkoo** [comment]
Please check [this video](https://imgur.com/a/D5QVhkq), I don't see any jumping in time when clicking. It is opening on 10:15

**Comment by ekkode** [comment]
Sorry, it seams ok now.

It was strange because I have set `@update:modelValue="setTime"` and the event was triggered automatically when the timer was opened with the values browser hour and minutes. Now when I check it seams ok.

Maybe it was something from my cache or something...

**Comment by Jasenkoo** [comment]
Ok, I will leave it for today if something is still wrong, otherwise will close the issue.
