### ISSUE TITLE
add hover text css variable

### ISSUE THREAD

**Issue by zynth17** [Vuepic/vue3-date-time-picker#39]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add new css variable for on hover text color

**Comment by Jasenkoo** [comment]
Will add in the next version

**Comment by zynth17** [comment]
> Will add in the next version

thanks!

**Comment by Jasenkoo** [comment]
Added in version [2.3.4](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.4)
