### ISSUE TITLE
Default Time

### ISSUE THREAD

**Issue by ravenshore** [Vuepic/vue3-date-time-picker#4]
Hi,

Is there currently a way to set default Time of Day.

1. After loading picker shows Current Date + Default Time ( predefined, e.g. 3:00 PM )
2. Date and Time can be modified by user.

If not - is that a planned feature? 
Thanks!

**Comment by Jasenkoo** [comment]
Will be added in the next version

**Comment by ravenshore** [comment]
Great, thanks!

**Comment by Jasenkoo** [comment]
Feature added in the [v2.0.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.0.0) release
