### ISSUE TITLE
add today button 

### ISSUE THREAD

**Issue by zynth17** [Vuepic/vue3-date-time-picker#40]
**Describe the solution you'd like**
instead of overwrite the action-select slot for creating a today button
it will be good to have it supported by default.

**Comment by Jasenkoo** [comment]
This was planned, will add in the next version

**Comment by zynth17** [comment]
> This was planned, will add in the next version

thankyou!

**Comment by Jasenkoo** [comment]
Added in version [2.3.4](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.4)
