### ISSUE TITLE
Add @opened event 

### ISSUE THREAD

**Issue by videk11** [Vuepic/vue3-date-time-picker#41]
Can you also add @opened (or some other name ) event. The same as closed event, opened event would be very usefull. Or maybe you had some other workaround in your mind? :) 

Thanks!

**Comment by Jasenkoo** [comment]
Will add

**Comment by Jasenkoo** [comment]
Added in the version [2.3.5](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.5)
