### ISSUE TITLE
Does the date range allows to only pick one date (the first) ? Not since 2.1.5 but allowed in 2.1.3/2.1.2

### ISSUE THREAD

**Issue by plalance** [Vuepic/vue3-date-time-picker#42]
**Describe the bug**
I started using your component in my Vue 3 project on version ^2.1.2.
The component with :range=true was allowing users to pick either one OR two dates but not since version 2.1.5.

Case 1 : dates model looks like [A Date, null] => It was possible in 2.1.2 and 2.1.3
Case 2 : dates model looks like [A Date, A Date] => It was possible in 2.1.2 and 2.1.3
 
Since 2.1.5 the case 1 is impossible, if user pick only one date (the first) then the "Select" button has no effect at all and the model is not updated with [Date, null] like it could before.

**To Reproduce**
1. Init a Datepicker component 

<Datepicker v-model="dateRange"
                                :range="true"
                                locale="fr"
                                :disabledDates="someDisabledDates"
                                :maxDate="maxDateForPicker"
                                placeholder="Sélectionner une date de début ou une période connue"
                                :enableTimePicker="false"
                                :startTime="{ hours: 0, minutes: 0 }"
                                @cleared="clearDateRange"/>

2. In your app, try to select only the first date of the range and click the button "select" to validate the selection => Nothing is happening.

**Expected behavior**

I wonder if this is a choice you made to not allow the selection of only 1 date for a range or if it is a bug, but the way it was in 2.1.2/2.1.3 was perfect for me, it allowed users to create à defined Range OR a possibly period without an end date (like for a Job contract with no determined end date...)

I then downragred from your latest version 2.3.4 to 2.1.2 and checked every single version, and the "break" seems to happen at 2.1.5 version.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome :  95.0.4638.69 (Build officiel) (64 bits)

**Comment by Jasenkoo** [comment]
Hmm, my idea was to only be able to select when both dates are selected. I would consider this as a bug in previous versions.

Will add this in the next version as an enhancement.

**Comment by plalance** [comment]
> Hmm, my idea was to only be able to select when both dates are selected. I would consider this as a bug in previous versions.
> 
> Will add this in the next version as an enhancement.

I understand you, it could be qualified of bug in older versions.

We'll stay fixed in 2.1.3 and upgrade to latest when your component will support this. Enhancements on the latest version are also useful to us. We'll keep an eye to your github.

Thank you.

**Comment by Jasenkoo** [comment]
Thanks, the new version will probably go in the next few days

**Comment by Jasenkoo** [comment]
Added in the version [2.3.5](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.5)

This behavior can be turned off by setting `partialRange` prop to `false`
