### ISSUE TITLE
scroll to move by month

### ISSUE THREAD

**Issue by zynth17** [Vuepic/vue3-date-time-picker#43]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
it will be good to have scrolling if the date is open, what i mean by scrolling is when the calendar open, we can move the datepicker using scroll and the date will move by month, i.e : scroll up will bring the datepicker move to previous month and vice versa. 

**Additional context**
will be usefull rather than have to click next or previous button

**Comment by Jasenkoo** [comment]
Interesting idea, will add it in the next version.

**Comment by Jasenkoo** [comment]
Added in [v2.3.6](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.3.6)

**Comment by zynth17** [comment]
i just notice that the scroll is on wrong behaviour? isn't scroll down supposed to go to next month and otherwise?

**Comment by zynth17** [comment]
@Jasenkoo

**Comment by Jasenkoo** [comment]
Yeah, but logically speaking, you go next month, meaning up + 1 and vice versa, I'll make an adjustment or config in the next version

**Comment by zynth17** [comment]
> Yeah, but logically speaking, you go next month, meaning up + 1 and vice versa, I'll make an adjustment or config in the next version

make sense. i think give a config is a good solution
