### ISSUE TITLE
Additional Slots and Settings

### ISSUE THREAD

**Issue by N37d7W** [Vuepic/vue3-date-time-picker#44]
**AM / PM Button with is24 = FALSE**
Many attributes of the calendar (pictures, etc.) can be slotted in. One of the few missing slots that could be useful would be for the inline AM / PM selector when the is24 prop is false. It would be nice to allow for customization here for custom sliders, selectors, etc. to match the style of existing sites.

Also, the width of the AM / PM button is variable between the two selections, causing the time selector to shift over when selecting between the two. I've just overridden the CSS in .dp__pm_am_button to 43px for now, but don't believe this would be intended.

**Time Picker Overlay**
The time picker is currently just an overlay on the calendar. This doesn't allow for easy adjustment of the height on an inline calendar. For example, when switching to the time selector, adjusting the inline container size to match the content of only the time picker isn't easy because the calendar is still open behind it. It would be great to toggle these views with a v-show instead of overlaying them so each div can be adjusted independently.

**Comment by Jasenkoo** [comment]
Will add it in the next version

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included enhancmeents
