### ISSUE TITLE
Add support for id property on underlying input

### ISSUE THREAD

**Issue by weskubo-cgi** [Vuepic/vue3-date-time-picker#45]
It would be very helpful to be able to pass an id attribute to the Datepicker component. When needing to programmatically populate data in the input field (e.g. in testcafe tests) it's currently not possible to target the input directly with an id selector. Instead we have to put an id on an enclosing div and then drill down to the input via selectors.

**Comment by Jasenkoo** [comment]
Will add

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included enhancmeents

**Comment by weskubo-cgi** [comment]
I've tested this on 2.4.2 and it works great. Thanks.
