### ISSUE TITLE
Is it possible to add 'second' field to Time picker?

### ISSUE THREAD

**Issue by jkythc** [Vuepic/vue3-date-time-picker#46]
timePickerComponent seems no 'second' field. Is it possible to add 'second' field to Time picker?

**Comment by Jasenkoo** [comment]
Will be added

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included enhancmeents
