### ISSUE TITLE
It should be possible to not clear modelValue when a menu is opened or closed without actually submitting the selection.

### ISSUE THREAD

**Issue by Chuuone** [Vuepic/vue3-date-time-picker#47]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to open the menu without clearing the model-value immediately.

**Describe the solution you'd like**
It would be useful to have a setting to not automatically clear model-value on closeMenu + openMenu events. The model-value in this case would only be changed if you pressed "submit" or if auto-apply enabled when you finish clicking the second date.

**Describe alternatives you've considered**
The only alternative i see right now is to add a bunch of scaffolding to undo the behaviour manually by hooking into closeMenu event in some way.

**Additional context**

**Comment by Chuuone** [comment]
Closing as behaviour takes place in the documentations example so it must be something wrong with my own setup.

**Comment by Jasenkoo** [comment]
Ok, let me know if there is an issue. I plan on some documentation adjustments since in the code example, it is a demo that shows opposite behavior than the default.
