### ISSUE TITLE
some props are ignored

### ISSUE THREAD

**Issue by web-elements** [Vuepic/vue3-date-time-picker#48]
hi,
I'm not sure if this is a bug, but I'm consulting the documentation for a couple of days and I can't get through, so I start wonder if it might be a bug (or am I just dumb)

[this is an example of what I'm trying to do](https://codepen.io/web-elements/pen/YzxoEWd)

Some props like __clearable__ and __format__ are working, some other (__enableTimePicker__, __monthChangeOnScroll__ and __autoApply__) have no effect 🤷‍♂️

**Comment by Jasenkoo** [comment]
You are not dumb 😄, this is really strange behavior. Did you try using Vue CLI project and checking if it is working there?

This could be related to some babel config. I made some adjustments for Vue CLI 4 and 5 in one of the previous versions. So this can be potentially related to browser usage aka .min.js file. Let me know

**Comment by Jasenkoo** [comment]
Ok, never mind, figured it out. For multi-word props, use `-`. Who would have known 😄 

Change your code to this:

```vue
<Datepicker
	v-model="date"
	:enable-time-picker="false"
	:clearable="false"
	:month-change-on-scroll="false"
	:format="dateFormat"
	auto-apply 
/>
```

**Comment by web-elements** [comment]
it's working!!! 😭🥳
really, **THANK YOU**!💖

**Comment by Jasenkoo** [comment]
No problem, I didn't know either, will update the docs.
