### ISSUE TITLE
Form is inaccessible via keyboard.

### ISSUE THREAD

**Issue by lbzg** [Vuepic/vue3-date-time-picker#49]
**Describe the bug**
When datepicker is opened, there is no way to focus and select values via keyboard. 

**To Reproduce**
1. Click input field (datepicker opens, focus stays on input); focusing input with tab key does not open datepicker at all though.
2. Press tab (focus goes away from input and closes datepicker)

**Expected behavior**
1. Focus input (input emits focus event, datepicker opens, focus shifts to datepicker, input does not emit a blur event)
2. Pressing tab should cycle focus on datepicker elements, pressing arrows should increment/decrement values
3. Pressing space/enter should confirm selection (pressing esc should close the datepicker) and emit blur event.

**Screenshots**
video - https://drive.google.com/file/d/1O8y7BOiE4r-IdztgoqWwEDKgJZPh8nkP/view?usp=sharing

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Additional but closely connected feature request: Consider implementing @focus/@blur events. The ability to control and manage input via javascript is hindered because there is no sensible way of knowing when the input or datepicker was focued/blurred even with extensive workardounds.

**Comment by Jasenkoo** [comment]
Will add. I would consider this more of an enhancement instead of a bug.

**Comment by lbzg** [comment]
Actually there is option to open popup on focus - https://vue3datepicker.com/api/props/#textinputoptions 👍 accessibility issue (keyboard) still stands but overall its a solid plugin.

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included enhancmeents
