### ISSUE TITLE
Dates prior to 1970 cannot be selected

### ISSUE THREAD

**Issue by fabricio-gwadera** [Vuepic/vue3-date-time-picker#50]
I am developing a system where it is necessary to include the client's date of birth, and there are clients who are born before the year 1970.
I was really upset about not being able to change the date of this client, and only after a lot of researching, I noticed that any date before 1970 is blocked for selection.

**Comment by Jasenkoo** [comment]
You can use [yearRange prop](https://vue3datepicker.com/api/props/#yearrange) , default value is `[1970, 2100]`, adjust to your needs
