### ISSUE TITLE
add stop propagation on picker element

### ISSUE THREAD

**Issue by zynth17** [Vuepic/vue3-date-time-picker#51]
**Describe the bug**
if the calendar component place inside a popup with behaviour click outside the popup. the picker will autoclose the popup without selecting any value. 

**To Reproduce**
1. Create a popup component (modal)
2. make the modal have behaviour on autoclosing if click outside the modal
3. put the datepicker component inside the modal
4. open the datepicker and click on the picker 
5. See error

**Expected behavior**
should not closing the picker and modal, maybe add event stop propagation on the picker element?

**Comment by Jasenkoo** [comment]
What version are you using, this should be fixed, and did you create a custom popup or from some CSS framework?

**Comment by zynth17** [comment]
> What version are you using, this should be fixed, and did you create a custom popup or from some CSS framework?

using the latest version. im creating a custom popup and not using any framework.

**Comment by Jasenkoo** [comment]
Hmm, can you provide some demo code that I can look into, also, if you use some click outside directive, that can cause it to leave, you can try changing the teleport target to the modal body instead of the document body and see if that fixes the issue

**Comment by zynth17** [comment]
> Hmm, can you provide some demo code that I can look into, also, if you use some click outside directive, that can cause it to leave, you can try changing the teleport target to the modal body instead of the document body and see if that fixes the issue

here is the reproduction link.
https://stackblitz.com/edit/vitejs-vite-xcb4vn?file=src/components/Popup.vue

**Comment by Jasenkoo** [comment]
Tnx, will fix check it

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included fix
