### ISSUE TITLE
Date range picker. Change available dates after selecting the first date.

### ISSUE THREAD

**Issue by ismailduymaz** [Vuepic/vue3-date-time-picker#52]
After selecting the date, I want to update available dates reference first selected dates.  Is this possible?

**Comment by Jasenkoo** [comment]
I don't know how would you do that, you can always update the range programmatically if you don't want to readjust the range again.

If you have a suggestion on how this would work I am happy to hear it.

**Comment by ismailduymaz** [comment]
Thank you for your answer. I can get all values from update:modelValue. So is there an event that I can trigger after the initial date selection? How can I catch this?

**Comment by Jasenkoo** [comment]
You would need manual v-model binding in order to do this, I can add an event in the next version if needed.

```vue
<template>
    <Datepicker v-model="modelBind"></Datepicker>
</template>

<script lang="ts" setup>
import { ref, computed } from 'vue';

const date = ref(null);

const modelBind = computed({
get() {
   return date.value
}.
set(value) {
   // you can add here what you need to do on model change
   date.value = value
}
})
</script>
```

Or bind directly to date and use a watch hook or use `:modelValue` and `@update:modelValue` event and handle it in the method

**Comment by ismailduymaz** [comment]
Thank you for your help. When I use the date range selector, the calculation is done after the second date is selected. If you add this event to the next release I will wait for it.

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included enhancmeents
