### ISSUE TITLE
Is there any way to override an event from being emitted, specifically the @cleared event?

### ISSUE THREAD

**Issue by andrewgilliland** [Vuepic/vue3-date-time-picker#53]
I would like to be able to put an icon in the clear-icon slot, but not have it emit the the @cleared event. Is this possible? 

I have tried @clear.stop, but the @cleared event still occurs. Many thanks for building this!

**Comment by Jasenkoo** [comment]
Currently not, I will see what I can do about it.

**Comment by andrewgilliland** [comment]
Thanks! I just found the clearable props in the docs and will use that currently.

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included enhancmeents
