### ISSUE TITLE
Now button crashes datepicker

### ISSUE THREAD

**Issue by tomIQME** [Vuepic/vue3-date-time-picker#54]
Hey,

first of all thanks for this datepicker component. I really like it. 
Unfortunately I discovered a bug with the now button.

**Describe the bug**
If I have a one screen calendar for a date range and click on the now button I am not able to select a new date or date range.

**To Reproduce**
1. implement datepicker as follows:

`<Datepicker
        :enableTimePicker="false"
        :locale="'de-DE'"
        :range="true"
        :twoCalendars="false"
        :format="'dd.MM.yyyy'"
        :showNowButton="true"
        v-model="date"
      ></Datepicker>`
      
2. open picker and select a date range
3. click on now button
4. selected range disappears and I am not able to select a new date

**Expected behavior**
After I click on the now button I should be able to select a new date range.

**Desktop (please complete the following information):**
 - OS: macOS 12.0.1 
 - Browser: Chrome v. 96.0.4664.55

**Comment by Jasenkoo** [comment]
WIll add it in the next version, this is both an issue and an enhancement, since it was originally intended for singe date usage

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included both fix and support for range mode
