### ISSUE TITLE
when weekStart="1" and the first day of the month is sunday(0), you will get the wrong calendar.

### ISSUE THREAD

**Issue by guo-junxian** [Vuepic/vue3-date-time-picker#55]
**Describe the bug**

when `weekStart="1"` and the first day of the month is sunday(`0`),
you will get the wrong calendar.

**Screenshots**

when `weekStart="0"` :
![image](https://user-images.githubusercontent.com/95405436/144381479-ee4e80b5-935b-4918-9bae-081e1602e89b.png)

when `weekStart="1"`  the wrong calendar :
![image](https://user-images.githubusercontent.com/95405436/144381538-49ffd0b2-d5e2-4fdc-9523-b86b4d24c8ec.png)

**Comment by Jasenkoo** [comment]
Will fix

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included fix
