### ISSUE TITLE
how to resize it. Example size="sm" or size="md",...

### ISSUE THREAD

**Issue by trandinhhuong** [Vuepic/vue3-date-time-picker#57]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jasenkoo** [comment]
Sice can by adjusted by overriding default classes, will see to add some easer configuration.

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with scss support for sizing
