### ISSUE TITLE
startTime has no effect in timePicker only mode

### ISSUE THREAD

**Issue by TheVaan** [Vuepic/vue3-date-time-picker#58]
**Describe the bug**
Using startTime in timePicker only mode has no effect.

**To Reproduce**
Add startTime to a <Datepicker timePicker /> element:
https://codesandbox.io/s/vue3-date-time-picker-demo-forked-mv7fd?file=/src/components/Demo.vue
For comparison I added a normal Datepicker where startTime has effect when entering time selection.

**Expected behavior**
In timePicker only mode the startTime should be used as default, not the current system time.

**Comment by Jasenkoo** [comment]
Will be fixed in the next version

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included fix
