### ISSUE TITLE
Disabled dates range or function to filter dates before specific date

### ISSUE THREAD

**Issue by vanling** [Vuepic/vue3-date-time-picker#60]
**Is your feature request related to a problem? Please describe.**
<img width="620" alt="Schermafbeelding 2021-12-05 om 17 27 27" src="https://user-images.githubusercontent.com/50699657/144754823-bbb619f4-e572-4a0a-baf7-77ce1ac2054a.png">

I have 2 date selectors and I don't want to use the range selection. But i do want to disable some dates in the second datepicker based on the value of the first datepicker

**Describe the solution you'd like**
I would love for a more simple way to disable all dates in the second datepicker before the selected date from the first datepicker.

**Describe alternatives you've considered**
Using a computed disabledDates with an array of al dates prior to selected date

If there is anything i missed that would already make this possible you can slap me with a fish 🥲

**Comment by vanling** [comment]
I've see another date picker before where disabled-dates could be a function and i think it was called on every displayed date.

```
disabledDate(date) {
  if(date < new Date('11-11-1111')) {
    return false 
  }
  return true
}
```

**Comment by Jasenkoo** [comment]
> I've see another date picker before where disabled-dates could be a function and i think it was called on every displayed date.
> 
> ```
> disabledDate(date) {
>   if(date < new Date('11-11-1111')) {
>     return false 
>   }
>   return true
> }
> ```

That is a nice and simple solution, will add it

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with included enhancements. You can now use both array or a custom function

**Comment by vanling** [comment]
@Jasenkoo Works flawlessly, thanks!
