### ISSUE TITLE
bug on scroll year not changed

### ISSUE THREAD

**Issue by zynth17** [Vuepic/vue3-date-time-picker#61]
**Describe the bug**
if we scroll the month from dec to january, the year is not changing to the next year

**Expected behavior**
supposed to change the year on scroll dec to the next january

**Comment by Jasenkoo** [comment]
Will be included in the next version, already covered (71fc2394dfaf3a0b44d0acd858727feaf95df503)

**Comment by zynth17** [comment]
> Will be included in the next version, already covered ([71fc239](https://github.com/Vuepic/vue3-date-time-picker/commit/71fc2394dfaf3a0b44d0acd858727feaf95df503))

all right! thanks! any eta on the release of next version?

**Comment by TheVaan** [comment]
> > Will be included in the next version, already covered ([71fc239](https://github.com/Vuepic/vue3-date-time-picker/commit/71fc2394dfaf3a0b44d0acd858727feaf95df503))
> 
> any eta on the release of next version?

<img width="452" alt="image" src="https://user-images.githubusercontent.com/1108485/144821554-e865e89d-26d6-43ee-a215-3568d07413f4.png">

9 days to go :)

**Comment by zynth17** [comment]
> > any eta on the release of next version?
> 
> <img alt="image" width="452" src="https://user-images.githubusercontent.com/1108485/144821554-e865e89d-26d6-43ee-a215-3568d07413f4.png">
> 
> 9 days to go :)

thanks!

**Comment by Jasenkoo** [comment]
It is currently in the testing phase, if everything is ok, it might be on weekend, will see.
