### ISSUE TITLE
Is there a way to set the timezone for the date-time-picker ? I would like to set the timezone to UTC to match my server side timezone.

### ISSUE THREAD

**Issue by manjunathpadolkar** [Vuepic/vue3-date-time-picker#62]
**Describe the bug**
I would like to set the timezone for the date picker to UTC. By default what I notice is that it picks the timezone from the browser. 

**To Reproduce**
1. I am trying to pass disabled dates as an array to the plugin via the `:disabledDates="disabledDates"` prop.
2. Note that the dates values that I am passing are in UTC format fetched from the server.
3. Now If I change my mac timezone to IST it disables the dates as expected but then if I change the my mac timezone to EST the disabled dates are offset by one day.

**Expected behavior**
I should be able to specify timezone to the plugin.

**Screenshots**
IST Timezone 
![image](https://user-images.githubusercontent.com/15189529/144910232-a2f2f0fe-f6e1-46be-8c4d-2f7e9641fe41.png)

EST timezone
![image](https://user-images.githubusercontent.com/15189529/144910270-cbd88812-b4fa-4ffe-b8b1-199041adf85c.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox
 - Version 94

**Comment by Jasenkoo** [comment]
This is currently not possible, however, I did plan to add it. I will see how much time it will take, so it may not be in the next version, but in the version after.

**Comment by SohMahmood** [comment]
Wow, I was just about to write an issue about something similar. On my computer at home the datepicker works flawlessly but if I am on my computer at work then all the dates are offset by 1. I am not sure what was causing this, it could be a timezone issue as with OP.

Interestingly, on my work computer, if I print a console.log of my date being returned with a custom format, it will print the right date and then print again with the date offset by a day.

**Comment by Jasenkoo** [comment]
Could be, will see if the issue is resolved when the timezone support is added.

**Comment by Jasenkoo** [comment]
Version [2.4.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0) is now live with an included fix. Timezone will now not affect provided dates. However, there is no way to implement a specific timezone, you have to work with local in the browser. Only timezone offset can be set.
