### ISSUE TITLE
How to assign setAttribute  in input?

### ISSUE THREAD

**Issue by trandinhhuong** [Vuepic/vue3-date-time-picker#63]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by trandinhhuong** [comment]
How to validate in the text input?

**Comment by Jasenkoo** [comment]
In the upcoming version, you would be able to pass `id` to the input field, and then do whatever is needed with the input.

Regarding the validation part, most of the Vue validation libraries are doing validation based on the v-model.

**Comment by Jasenkoo** [comment]
Ref (#45)
