### ISSUE TITLE
Two clicks required after clear when using the `#clear-icon` slot

### ISSUE THREAD

**Issue by misha** [Vuepic/vue3-date-time-picker#64]
**Describe the bug**

When using the `#clear-icon` slot with a custom element, clicking clear also seems to remove focus from the component, so you have to click again to focus, then again to re-open.

**To Reproduce**
1. Use the `#clear-icon` slot - anything works, ie. (with Tailwind) `<div class="h-4 w-4 bg-green-500" />`.
2. Click the clear icon.
3. Click the input box. (Nothing happens.)
4. Click the input box again to finally open the calendar.

**Expected behavior**

The calendar _should_ open on the first click.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 96.0.4664.45 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

N/A

**Additional context**

N/A

**Comment by Jasenkoo** [comment]
This is fixed in the new version [2.3.5](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.0). However, make sure to call `clear` function provided in the slot props, since it is now exposed and not done automatically  (#53)
