### ISSUE TITLE
model value become UTC format

### ISSUE THREAD

**Issue by mytc** [Vuepic/vue3-date-time-picker#67]
I use this for an datetime input for a form that will later send to server for storing.

However, the value that in model is in UTC format which is not a desired value. 

For eg:
The component show `2021-12-14 14:51:02`  but when I checked the model value, it become `2021-12-14T06:51:37.478Z`. 
Is this a bug or intended ?
How can I fix this issue to get the value as it seen in the component?

**Comment by Jasenkoo** [comment]
It is a string representation of the date object.

The format you are referring to `2021-12-14 14:51:02` is formatted date via `date-fns` [format](https://date-fns.org/v2.27.0/docs/format) function.

To achieve something like that with plain JavaScript you can do the following

```js
const dateFormat = (vModelDate) => {
  const date = new Date(vModelDate);
  return `${date.getFullYear()}-${date.getMonth()}-${date.getDate()} ${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}`
}
```

**Comment by mytc** [comment]
Thanks.

End up parse it in the server side.
