### ISSUE TITLE
TimePicker range does not work

### ISSUE THREAD

**Issue by entioentio** [Vuepic/vue3-date-time-picker#69]
**Describe the bug**
TimePicker range opens correctly but nothing heppens after selecting times and clicking on "select".

**To Reproduce**
1. Go to the playground
2. change the component code to the snippet below
3. try selecting date, i doesnt work. Opens correctly but does not work.

```<template>
  <div>
    <Datepicker v-model="date" timePicker range/>
  </div>
</template>

<script>
import { ref } from "vue";
import Datepicker from "vue3-date-time-picker";
import "vue3-date-time-picker/dist/main.css";

export default {
  name: "Demo",
  components: {
    Datepicker,
  },
  setup() {
    const date = ref();
    
    const startDate = new Date();
    const endDate = new Date(new Date().setDate(startDate.getDate() + 7));
    date.value = [startDate, endDate];

    return {
      date,
    };
  },
};
</script>
```

**Expected behavior**
It allows selecting a date

**Desktop (please complete the following information):**
 - OS PopOs
 - Browser Brave
 - Version 1.33.106

**Comment by Jasenkoo** [comment]
I think think this is not an issue since `v-model` with time picker is not working with dates

Correct type would be `{ hours: number | string; minutes: number  | string; seconds?: number | string }` and in `range` mode 2 of these objects are in an array.

**Comment by entioentio** [comment]
Right, I'll check it next week, thanks for explanation. Then it'd certainly be good to have this explained better in the documentation. Or is it just me? I could have missed it. Was searching long but whilst on a long and boring meeting. Could have missed it.

**Comment by Jasenkoo** [comment]
No problem, will move `v-model` docs higher, if you still have the issue, feel free to reopen it 😃
