### ISSUE TITLE
Hide "clear" icon in the input field

### ISSUE THREAD

**Issue by Gumlokt** [Vuepic/vue3-date-time-picker#71]
**Is your feature request related to a problem? Please describe.**
I'd like to create my own "clear" button and hide or remove original "clear" icon.

**Describe the solution you'd like**
The easiest way to solve my problem is to add prop hideClearIcon for hiding "clear" icon (like hideInputIcon to hide calendar icon).

![vue3dtp](https://user-images.githubusercontent.com/9348101/147046402-6a80fba4-6731-4112-8d42-f86c1403a96f.jpg)

**Comment by Jasenkoo** [comment]
There is a slot for a custom clear icon, check [here](https://vue3datepicker.com/api/slots/#clear-icon)

You can also disable clear icon by setting `clearable` to `false`
