### ISSUE TITLE
'required' option wanted

### ISSUE THREAD

**Issue by batuotasis** [Vuepic/vue3-date-time-picker#72]
**Is your feature request related to a problem? Please describe.**
We use standard HTML form validation. In case datepicker field value is empty and required, user is able to submit form. 

**Describe the solution you'd like**
Add `required` prop, just like existing `disabled`, `readonly`, etc. It should add `required` attribute to html input element.

**Comment by Jasenkoo** [comment]
Added in [v2.4.4](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.4.4)
