### ISSUE TITLE
Separate CSS classes to set border color for input field and calendar menu

### ISSUE THREAD

**Issue by Gumlokt** [Vuepic/vue3-date-time-picker#74]
**Is your feature request related to a problem? Please describe.**
I haven’t found a way to disable the border for the input field and keep it for the calendar menu at the same time. 

**Describe the solution you'd like**
I'd like to have separate CSS class to set the border color for the calendar menu (something like --dp-calendar-border-color). In other words, it would be nice to have 2 different CSS classes: one CSS class for setting the border color for the input field and a second CSS class for the calendar menu.

**Comment by Jasenkoo** [comment]
Included in the [v2.5.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.5.0)
