### ISSUE TITLE
Allow to display more than 2 months at once in mobile view

### ISSUE THREAD

**Issue by scheruku9** [Vuepic/vue3-date-time-picker#75]
**Is your feature request related to a problem? Please describe.**
I would like to have a way to specify number of months the calendar can display in mobile view. Currently maximum of two months can be displayed at once, but I would like to have an option to increase it.

**Describe the solution you'd like**
Passing a prop with the number of months to be displayed at once in mobile view.

**Comment by dzlerner** [comment]
This would be very helpful in being able to craft a responsive UI! We're trying to be able to allow users to scroll vertically on mobile devices, as opposed to relying on the left/right pagination through months. 

If we stack the months vertically but we're limited to 2 months, users would still need to paginate left and right.

**Comment by Jasenkoo** [comment]
Will be added 👍.

**Comment by Jasenkoo** [comment]
Included in the [v2.5.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.5.0)
