### ISSUE TITLE
Add a new `inlineWithInput` prop to show input and calendar menu by default

### ISSUE THREAD

**Issue by LiliFelsen** [Vuepic/vue3-date-time-picker#77]
**Is your feature request related to a problem? Please describe.**
I need to be able to show the input and the calendar open by default. I tried using the `inline` prop but that removes the input entirely.

**Describe the solution you'd like**
Similar to the current `inline` prop, maybe have another one like `inlineWithInput` that will keep the input field visible even when the calendar menu is open by default.

**Comment by Jasenkoo** [comment]
I think there is no need for adding a new prop since this can be achieved without it anyway, please take a look at [this example](https://codesandbox.io/s/vue3-date-time-picker-demo-forked-ktx9d?file=/src/components/Demo.vue).

**Comment by LiliFelsen** [comment]
Thanks for getting back to me! Maybe I'm missing something but with the example you sent, it wouldn't be possible to type in the input in order to select the date, right? Or would that work?

**Comment by Jasenkoo** [comment]
It would not be possible, however adding an input with inline kinda defeats the point of the inline. I think I will just expose the parse date function and going with the above example should cover your case.

**Comment by Jasenkoo** [comment]
Included in the [v2.5.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.5.0)
