### ISSUE TITLE
Possibly typo in index.d.ts?

### ISSUE THREAD

**Issue by SohMahmood** [Vuepic/vue3-date-time-picker#78]
Trying to run my vuejs project with vite build and it shoots an error:

\\
node_modules/vue3-date-time-picker/index.d.ts:176:20 - error TS2304: Cannot find name 'Locale'.

176     formatLocale?: Locale;
\\

Changing the line to formatLocale?: boolean fixes the issue. Not sure if just on my side or typo in code.

**Comment by Jasenkoo** [comment]
It is a bug, in my IDE it was auto inherited from the `date-fns`, will extract it.

**Comment by Jasenkoo** [comment]
Included in the [v2.5.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.5.0)
