### ISSUE TITLE
Add field name attribute

### ISSUE THREAD

**Issue by mohammedeisa** [Vuepic/vue3-date-time-picker#80]
**Is your feature request related to a problem? Please describe.**
I'm not able to set a name for the datetime picker.

I've checked the code, I think that the DatepickerInput.vue component is responsible for printing the input and its attributes.
I don't see a name attribute in the field:
<input
                ref="inputRef"
                :id="uid ? `dp-input-${uid}` : undefined"
                :class="inputClass"
                :placeholder="placeholder"
                :disabled="disabled"
                :readonly="readonly"
                :required="required"
                :value="inputValue"
                @input="handleInput"
                @keydown.enter="handleEnter"
                @keydown.tab="handleTab"
                @blur="handleBlur"
                @focus="handleFocus"
            />

**Comment by Jasenkoo** [comment]
Included in the [v2.5.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.5.0)

**Comment by mohammedeisa** [comment]
Thanks :)
