### ISSUE TITLE
Is possible to disable Chrome input autocomplete?

### ISSUE THREAD

**Issue by jkythc** [Vuepic/vue3-date-time-picker#83]
![2022-01-21 175747](https://user-images.githubusercontent.com/25739531/150507848-902683b6-3860-4af0-8080-a70195833573.png)

Is there are way to assign `autocomplete="off"` to input field? Thanks.
`<input class="dp__input dp__input_icon_pad" autocomplete="off">`

**Comment by Jasenkoo** [comment]
Will add in the upcoming version

**Comment by Jasenkoo** [comment]
Included in the [v2.5.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.5.0)
