### ISSUE TITLE
Feature Select and jump

### ISSUE THREAD

**Issue by arnyee** [Vuepic/vue3-date-time-picker#87]
Hi i Really love your project, I need a little help, I didn't find a solution for my problem yet, I hope you can help me.

It's not a big problem, but i think it would be nice if there will be option when I set it true, and I select a date It automaticly jump to the Hour grid and after I select an hour than It jump to the minute grid.  
In my experience, several users like this date time picker yet they have to click a lot to set the correct date and time.

Is there any solution for this yet, or are you planing to do something similar to this?

I hope you can help me as soon as possible!

**Comment by Jasenkoo** [comment]
WIll be added, not in the upcoming version, but after that.
