### ISSUE TITLE
Disable time picker option

### ISSUE THREAD

**Issue by onurusluca** [Vuepic/vue3-date-time-picker#90]
It would be good to have a option to disable the time picker just like "disableMonthYearSelect" option.

**Comment by onurusluca** [comment]
My bad. There is an option for that: https://vue3datepicker.com/api/props/#enabletimepicker
    <Datepicker v-model="date" :enableTimePicker="false" />

**Comment by Jasenkoo** [comment]
Included in the [v2.5.0](https://github.com/Vuepic/vue3-date-time-picker/releases/tag/v2.5.0)
