### ISSUE TITLE
Configuring `minutesGridIncrement` and `filters` doesn't work

### ISSUE THREAD

**Issue by catherineluse** [Vuepic/vue3-date-time-picker#91]
The `minutesGridIncrement` is broken in the documentation example here https://vue3datepicker.com/api/props/#minutesgridincrement

In the example, `minutesGridIncrement` is configured as 2. But when I pick the minutes in the above linked documentation example they are incremented by 1.

Configuring the `minutesGridIncrement` value had no effect in my code either. This configuration resulted in minutes being incremented by 1:

```
<DatePicker
    v-model="time"
    :minutes-grid-increment="30"
  />
```

I tried to achieve the same effect (allowing only 00 and 30 minute times to be configured) by adding filters in the `filters` property. But disabling specific filters using the config shown in this example https://vue3datepicker.com/api/props/#filters also had no effect.

**Comment by Jasenkoo** [comment]
What you are referring to is a `minutesIncrement` prop, described [here](https://vue3datepicker.com/api/props/#minutesincrement).

Grid increments props are for overlay values. Filters are mainly used for disabling some specific values.
