### ISSUE TITLE
MonthPicker, TimePicker not working

### ISSUE THREAD

**Issue by s-fog** [Vuepic/vue3-date-time-picker#92]
Hi. Have strange issue. Iam doing just same in docs, and picker not working.
Html
`<Datepicker v-model="mmonth" monthPicker />`
App.vue
`const ...,
mmonth = ref({
                month: new Date().getMonth(),
                year: new Date().getFullYear()
            })
return {
...,
mmonth
...
}
`
Renders regular datepicker without any default value.
![image](https://user-images.githubusercontent.com/10043516/151694741-10d8b685-36b2-451d-a10a-481570ac25fd.png)
Opening as regular datepicker. I want monthpicker.
![image](https://user-images.githubusercontent.com/10043516/151694770-ab398ed7-cb25-45cc-b69a-852333ecbcaf.png)

I tried initialize mmonth.month and mmonth.year inside onMounted method, but it works the same way. 
I tried range datepicker and it works as expected. But this no.
What am i doing wrong?

**Comment by Jasenkoo** [comment]
Are you using component in the browser script tag? Or some bundler like Vue-CLI or Vite?

**Comment by s-fog** [comment]
Thanks for reply! Iam using laravel + vue 
`mix.js("resources/js/app.js", "public/js")
    .vue()`
Launching is npm run watch

**Comment by Jasenkoo** [comment]
Can you try passing prop like `month-picker ` and tell me if it works

**Comment by s-fog** [comment]
It works! Thank you so much. I it described somewhere in docs?

**Comment by Jasenkoo** [comment]
There is info when you register the component in the browser, I guess, this is happening when using .min.js build, I'll see what is going on there.
