### ISSUE TITLE
Range enhancement proposals

### ISSUE THREAD

**Issue by cslettengren** [Vuepic/vue3-date-time-picker#93]
Wow, great work so far!
Two enhancement proposals:
1. Possibility to make the start date or end date in a range read-only (not changeable), so that only one of the two can be changed.
2. Possibility to set a min-range and max-range.

**Comment by Jasenkoo** [comment]
Tnx, will be added

**Comment by cslettengren** [comment]
Hmm, how could that do the job? For example I would like to be able to chose from all the dates of 2022 but always at least four days but eight days at the most?

**Comment by Jasenkoo** [comment]
> Hmm, how could that do the job? For example I would like to be able to choose from all the dates of 2022 but always at least four days but eight days at the most?

Ok, I didn't understand it properly, will add it.

**Comment by cslettengren** [comment]
That would really be awesome!
