### ISSUE TITLE
prevent month navigation outside minDate/maxDate

### ISSUE THREAD

**Issue by gerritvanaaken** [Vuepic/vue3-date-time-picker#94]
Users are able to navigate to a month that is in the past (or before the defined minDate of the date picker). That confuses them potentially.

I would like an option that prevents displaying the month view outside the defined minDate and maxDate of this datepicker instance!

**Comment by Jasenkoo** [comment]
I am aware of this issue, it will be fixed in the next version

**Comment by gerritvanaaken** [comment]
Can’t wait for 2.6.0 ;-)

**Comment by gerritvanaaken** [comment]
Thanks for adding this feature. Two remarks, though:

1. Shouldn’t it be sufficient if one of the two props "minDate" or "maxDate" is given? Currently, both are needed, so I would have to set some fantasy date in the future as "maxDate".
2. In my quick test, I have set "minDate" to "now". I changed the month to March, but could not get back to February afterwards. Maybe something wrong with my reactivity, maybe a bug.

**Comment by Jasenkoo** [comment]
@gerritvanaaken 


> 1. Shouldn’t it be sufficient if one of the two props "minDate" or "maxDate" is given? Currently, both are needed, so I would have to set some fantasy date in the future as "maxDate"

Hmm, I will check that, it should work if only one is added



> 2\. In my quick test, I have set "minDate" to "now". I changed the month to March, but could not get back to February afterwards. Maybe something wrong with my reactivity, maybe a bug.

There is an issue that will be fixed in the upcoming version (check #99)
