### ISSUE TITLE
Seconds not working in range time picker

### ISSUE THREAD

**Issue by cslettengren** [Vuepic/vue3-date-time-picker#95]
`<Datepicker v-model="selectedDate" placeholder="Select Date" enable-seconds range />`

Second are showing in time-picker, but they can't be changed.

Seems like second-support was never added to the range time picker.

<img width="707" alt="image" src="https://user-images.githubusercontent.com/419076/152749576-82136e42-5e95-40ce-8a93-a8298b9348dc.png">

**Comment by Jasenkoo** [comment]
Hah, I overlooked it. Will be fixed.
