### ISSUE TITLE
Pick the time without toggling to the time picker, but instead have the time picker right below the date picker.

### ISSUE THREAD

**Issue by shawn-p-m** [Vuepic/vue3-date-time-picker#96]
**Is your feature request related to a problem? Please describe.**
Seeing the time picker right away and being able to change without togging between the time picker and the date picker saves time.

**Describe the solution you'd like**
A prop called something like "timePickerBelowCalendar" that is a boolean determining whether timepicker has it's own screen or it is on its own.

**Describe alternatives you've considered**
A slot that goes where the clock toggle button is. In there a custom timepicker layout can be built with slotprops.

**Additional context**
Really great library! Thanks for your consideration. Nothing else for me to add.

**Comment by shawn-p-m** [comment]
@Jasenkoo Is your team okay with me adding this feature or interested in doing this yourselves?

**Comment by Jasenkoo** [comment]
Check this [example](https://vue3datepicker.com/api/components/#timepickercomponent), I think this should cover your request.
